//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvcSp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Afp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Afp()
        {
            this.Empleados = new HashSet<Empleados>();
        }

        [Key]
        public int Cod_Afp { get; set; }

        [Display(Name="Nombre_AFP")]
        [Required(ErrorMessage ="Dato Obligatorio")]
        public string Nom_Afp { get; set; }

        [Display(Name = "Porcentaje")]
        [Required(ErrorMessage = "Dato Obligatorio")]
        public Nullable<decimal> Porc_Desc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
       

        //public Afp()
        //{
        //    this.Cod_Afp = Int_NullValue;
        //    this.Nom_Afp = String_NullValue;
        //}
    }
}
