//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvcSp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargas_Familiares
    {
        public int Id_Tram_Carg { get; set; }
        public string Tramo { get; set; }
        public string Desde { get; set; }
        public string Hasta { get; set; }
        public string ValorPagarCarg { get; set; }
    }
}
