//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvcSp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleados()
        {
            this.Carg_Familiar = new HashSet<Carg_Familiar>();
        }
    
        public string Rut_Empleado { get; set; }
        public string Nombre { get; set; }
        public string ApePat { get; set; }
        public string ApeMat { get; set; }
        public int Id_Depto { get; set; }
        public int Id_Carg { get; set; }
        public string Anexo { get; set; }
        public string EmailEmp { get; set; }
        public string Fecha_Incorporacion { get; set; }
        public string Rut_Empresa { get; set; }
        public int Id_Sexo { get; set; }
        public int Id_Nac { get; set; }
        public int Cod_Afp { get; set; }
        public int Cod_Salud { get; set; }
        public string Calle_Pje { get; set; }
        public string NumCasa { get; set; }
        public string Vill_Pobl { get; set; }
        public int Comuna_Id { get; set; }
        public int Provincia_Id { get; set; }
        public string Fono { get; set; }
        public string Persona_Emergencia { get; set; }
        public string Fono_Emergencia { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Fecha_Nacimiento { get; set; }
        public byte[] Foto_Usuario { get; set; }
        public string Fecha_Despido { get; set; }
        public string Retirado { get; set; }
    
        public virtual Afp Afp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carg_Familiar> Carg_Familiar { get; set; }
        public virtual Cargos Cargos { get; set; }
        public virtual Comuna Comuna { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Sexo Sexo { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Nacionalidad Nacionalidad { get; set; }
        public virtual Salud Salud { get; set; }
        public virtual Provincia Provincia { get; set; }
    }
}
