//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvcSp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Empleados = new HashSet<Empleados>();
        }

        [Key]
        public int Id_Empresa { get; set; }

        [Required(ErrorMessage = "Dato Obligatorio")]
        public string Rut_Empresa { get; set; }

        [Required(ErrorMessage = "Dato Obligatorio")]
        public string Nombre_Empresa { get; set; }

        [Required(ErrorMessage = "Dato Obligatorio")]
        public string Calle_Pje_Avda { get; set; }

        [Required(ErrorMessage = "Dato Obligatorio")]
        public string Numero { get; set; }

        [Required(ErrorMessage = "Dato Obligatorio")]
        public string Vill_Pobl { get; set; }

        [Required(ErrorMessage = "Dato Obligatorio")]
        public int Comuna_Id { get; set; }
        public int Provincia_Id { get; set; }

        [Display(Name = "Fono Empresa")]
        [Required(ErrorMessage = "Dato Obligatorio")]
        public string fono { get; set; }

        [Required(ErrorMessage = "Dato Obligatorio")]
        [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "E-mail Empresa No Es Valido")]
        public string emailemp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
    }
}
