//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvcSp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liquidacion_Sueldo
    {
        public int Id_Liq { get; set; }
        public Nullable<int> Tipo_Renumeracion { get; set; }
        public string Rut_Empleado { get; set; }
        public Nullable<System.DateTime> Fecha_Liquidacion { get; set; }
        public string Sueldo_Base { get; set; }
        public string Remuneracion_Imponible { get; set; }
        public string Cant_Carg_Fam { get; set; }
        public string PagoTot_Carg_Fam { get; set; }
        public string Movilizacion { get; set; }
        public string Colacion { get; set; }
        public Nullable<int> Cod_Afp { get; set; }
        public string Cotizacion_Previsional { get; set; }
        public string Adicional_Prevision { get; set; }
        public Nullable<int> Cod_Salud { get; set; }
        public string Cotizacion_Salud { get; set; }
        public string Adicional_Salud { get; set; }
        public string Otros_Descuentos { get; set; }
        public string Alcance_Liquido { get; set; }
        public string Vales_Anticipos { get; set; }
        public string Sueldo_Liquido { get; set; }
    }
}
