//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvcSp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {

        [Key]
        public int Id { get; set; }

        [Display(Name = "Nombre Usuario")]
        public string Username { get; set; }

        [Display(Name = "Correo Usuario")]
        public string Email { get; set; }

        [Display(Name = "Clave Usuario")]
        public string Password { get; set; }

        [Display(Name = "Confirme Clave Usuario")]
        public string ConfirPassword { get; set; }
    }
}
