//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvcSp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EmpleadosEntities : DbContext
    {
        public EmpleadosEntities()
            : base("name=EmpleadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afp> Afp { get; set; }
        public virtual DbSet<Carg_Familiar> Carg_Familiar { get; set; }
        public virtual DbSet<Cargas_Familiares> Cargas_Familiares { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<Comuna> Comuna { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Nacionalidad> Nacionalidad { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<Salud> Salud { get; set; }
        public virtual DbSet<Sexo> Sexo { get; set; }
        public virtual DbSet<TablImpDiario> TablImpDiario { get; set; }
        public virtual DbSet<TablImpMensual> TablImpMensual { get; set; }
        public virtual DbSet<TablImpQuincenal> TablImpQuincenal { get; set; }
        public virtual DbSet<TablImpSemanal> TablImpSemanal { get; set; }
        public virtual DbSet<Tipo_Remuneracion> Tipo_Remuneracion { get; set; }
        public virtual DbSet<Seg_Cesantia> Seg_Cesantia { get; set; }
        public virtual DbSet<Liquidacion_Sueldo> Liquidacion_Sueldo { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<SP_Autoriza_Result> SP_Autoriza(string user_Id, string clave)
        {
            var user_IdParameter = user_Id != null ?
                new ObjectParameter("User_Id", user_Id) :
                new ObjectParameter("User_Id", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Autoriza_Result>("SP_Autoriza", user_IdParameter, claveParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int Sp_Del_Carga_Familiar(string rut_benf)
        {
            var rut_benfParameter = rut_benf != null ?
                new ObjectParameter("rut_benf", rut_benf) :
                new ObjectParameter("rut_benf", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Del_Carga_Familiar", rut_benfParameter);
        }
    
        public virtual int Sp_Del_Empleados(string rut_Empl)
        {
            var rut_EmplParameter = rut_Empl != null ?
                new ObjectParameter("Rut_Empl", rut_Empl) :
                new ObjectParameter("Rut_Empl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Del_Empleados", rut_EmplParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int Sp_Ins_Afp(string nomb_Afp, Nullable<decimal> porcDesc)
        {
            var nomb_AfpParameter = nomb_Afp != null ?
                new ObjectParameter("Nomb_Afp", nomb_Afp) :
                new ObjectParameter("Nomb_Afp", typeof(string));
    
            var porcDescParameter = porcDesc.HasValue ?
                new ObjectParameter("PorcDesc", porcDesc) :
                new ObjectParameter("PorcDesc", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Ins_Afp", nomb_AfpParameter, porcDescParameter);
        }
    
        public virtual int Sp_Ins_Carg_Familiar(string rut_Benef, string nombre, string apPat, string apMat, string telefono1, string telefono2, Nullable<System.DateTime> fecha_Nac, Nullable<int> cod_Sexo, string calle_Pje, string num_Casa, string villa_Pobl, Nullable<int> comuna_Id, Nullable<int> provincia_Id, string email, string rut_Empleado, Nullable<int> id_Nac, string desc)
        {
            var rut_BenefParameter = rut_Benef != null ?
                new ObjectParameter("Rut_Benef", rut_Benef) :
                new ObjectParameter("Rut_Benef", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apPatParameter = apPat != null ?
                new ObjectParameter("ApPat", apPat) :
                new ObjectParameter("ApPat", typeof(string));
    
            var apMatParameter = apMat != null ?
                new ObjectParameter("ApMat", apMat) :
                new ObjectParameter("ApMat", typeof(string));
    
            var telefono1Parameter = telefono1 != null ?
                new ObjectParameter("Telefono1", telefono1) :
                new ObjectParameter("Telefono1", typeof(string));
    
            var telefono2Parameter = telefono2 != null ?
                new ObjectParameter("Telefono2", telefono2) :
                new ObjectParameter("Telefono2", typeof(string));
    
            var fecha_NacParameter = fecha_Nac.HasValue ?
                new ObjectParameter("Fecha_Nac", fecha_Nac) :
                new ObjectParameter("Fecha_Nac", typeof(System.DateTime));
    
            var cod_SexoParameter = cod_Sexo.HasValue ?
                new ObjectParameter("Cod_Sexo", cod_Sexo) :
                new ObjectParameter("Cod_Sexo", typeof(int));
    
            var calle_PjeParameter = calle_Pje != null ?
                new ObjectParameter("Calle_Pje", calle_Pje) :
                new ObjectParameter("Calle_Pje", typeof(string));
    
            var num_CasaParameter = num_Casa != null ?
                new ObjectParameter("Num_Casa", num_Casa) :
                new ObjectParameter("Num_Casa", typeof(string));
    
            var villa_PoblParameter = villa_Pobl != null ?
                new ObjectParameter("Villa_Pobl", villa_Pobl) :
                new ObjectParameter("Villa_Pobl", typeof(string));
    
            var comuna_IdParameter = comuna_Id.HasValue ?
                new ObjectParameter("Comuna_Id", comuna_Id) :
                new ObjectParameter("Comuna_Id", typeof(int));
    
            var provincia_IdParameter = provincia_Id.HasValue ?
                new ObjectParameter("Provincia_Id", provincia_Id) :
                new ObjectParameter("Provincia_Id", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var rut_EmpleadoParameter = rut_Empleado != null ?
                new ObjectParameter("Rut_Empleado", rut_Empleado) :
                new ObjectParameter("Rut_Empleado", typeof(string));
    
            var id_NacParameter = id_Nac.HasValue ?
                new ObjectParameter("Id_Nac", id_Nac) :
                new ObjectParameter("Id_Nac", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("Desc", desc) :
                new ObjectParameter("Desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Ins_Carg_Familiar", rut_BenefParameter, nombreParameter, apPatParameter, apMatParameter, telefono1Parameter, telefono2Parameter, fecha_NacParameter, cod_SexoParameter, calle_PjeParameter, num_CasaParameter, villa_PoblParameter, comuna_IdParameter, provincia_IdParameter, emailParameter, rut_EmpleadoParameter, id_NacParameter, descParameter);
        }
    
        public virtual int Sp_Ins_Cargos(string descr)
        {
            var descrParameter = descr != null ?
                new ObjectParameter("Descr", descr) :
                new ObjectParameter("Descr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Ins_Cargos", descrParameter);
        }
    
        public virtual int Sp_Ins_Depto(string nomDepto)
        {
            var nomDeptoParameter = nomDepto != null ?
                new ObjectParameter("NomDepto", nomDepto) :
                new ObjectParameter("NomDepto", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Ins_Depto", nomDeptoParameter);
        }
    
        public virtual int Sp_Ins_Empleados(string rut_Empleado, string nombre, string apePat, string apeMat, Nullable<int> id_Depto, Nullable<int> id_Carg, string anexo, string emailEmp, string fecha_Incorporacion, string rut_Empresa, Nullable<int> id_Sexo, Nullable<int> id_Nac, byte[] foto_Usuario, string fecha_Despido, string retirado, Nullable<int> cod_Afp, Nullable<int> cod_Salud, string calle_Pje, string numCasa, string vill_Pobl, Nullable<int> comuna_Id, Nullable<int> provincia_Id, string fono, string persona_Emergencia, string fono_Emergencia, string email, Nullable<System.DateTime> fecha_Nacimiento)
        {
            var rut_EmpleadoParameter = rut_Empleado != null ?
                new ObjectParameter("Rut_Empleado", rut_Empleado) :
                new ObjectParameter("Rut_Empleado", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apePatParameter = apePat != null ?
                new ObjectParameter("ApePat", apePat) :
                new ObjectParameter("ApePat", typeof(string));
    
            var apeMatParameter = apeMat != null ?
                new ObjectParameter("ApeMat", apeMat) :
                new ObjectParameter("ApeMat", typeof(string));
    
            var id_DeptoParameter = id_Depto.HasValue ?
                new ObjectParameter("Id_Depto", id_Depto) :
                new ObjectParameter("Id_Depto", typeof(int));
    
            var id_CargParameter = id_Carg.HasValue ?
                new ObjectParameter("Id_Carg", id_Carg) :
                new ObjectParameter("Id_Carg", typeof(int));
    
            var anexoParameter = anexo != null ?
                new ObjectParameter("Anexo", anexo) :
                new ObjectParameter("Anexo", typeof(string));
    
            var emailEmpParameter = emailEmp != null ?
                new ObjectParameter("EmailEmp", emailEmp) :
                new ObjectParameter("EmailEmp", typeof(string));
    
            var fecha_IncorporacionParameter = fecha_Incorporacion != null ?
                new ObjectParameter("Fecha_Incorporacion", fecha_Incorporacion) :
                new ObjectParameter("Fecha_Incorporacion", typeof(string));
    
            var rut_EmpresaParameter = rut_Empresa != null ?
                new ObjectParameter("Rut_Empresa", rut_Empresa) :
                new ObjectParameter("Rut_Empresa", typeof(string));
    
            var id_SexoParameter = id_Sexo.HasValue ?
                new ObjectParameter("Id_Sexo", id_Sexo) :
                new ObjectParameter("Id_Sexo", typeof(int));
    
            var id_NacParameter = id_Nac.HasValue ?
                new ObjectParameter("Id_Nac", id_Nac) :
                new ObjectParameter("Id_Nac", typeof(int));
    
            var foto_UsuarioParameter = foto_Usuario != null ?
                new ObjectParameter("Foto_Usuario", foto_Usuario) :
                new ObjectParameter("Foto_Usuario", typeof(byte[]));
    
            var fecha_DespidoParameter = fecha_Despido != null ?
                new ObjectParameter("Fecha_Despido", fecha_Despido) :
                new ObjectParameter("Fecha_Despido", typeof(string));
    
            var retiradoParameter = retirado != null ?
                new ObjectParameter("Retirado", retirado) :
                new ObjectParameter("Retirado", typeof(string));
    
            var cod_AfpParameter = cod_Afp.HasValue ?
                new ObjectParameter("Cod_Afp", cod_Afp) :
                new ObjectParameter("Cod_Afp", typeof(int));
    
            var cod_SaludParameter = cod_Salud.HasValue ?
                new ObjectParameter("Cod_Salud", cod_Salud) :
                new ObjectParameter("Cod_Salud", typeof(int));
    
            var calle_PjeParameter = calle_Pje != null ?
                new ObjectParameter("Calle_Pje", calle_Pje) :
                new ObjectParameter("Calle_Pje", typeof(string));
    
            var numCasaParameter = numCasa != null ?
                new ObjectParameter("NumCasa", numCasa) :
                new ObjectParameter("NumCasa", typeof(string));
    
            var vill_PoblParameter = vill_Pobl != null ?
                new ObjectParameter("Vill_Pobl", vill_Pobl) :
                new ObjectParameter("Vill_Pobl", typeof(string));
    
            var comuna_IdParameter = comuna_Id.HasValue ?
                new ObjectParameter("Comuna_Id", comuna_Id) :
                new ObjectParameter("Comuna_Id", typeof(int));
    
            var provincia_IdParameter = provincia_Id.HasValue ?
                new ObjectParameter("Provincia_Id", provincia_Id) :
                new ObjectParameter("Provincia_Id", typeof(int));
    
            var fonoParameter = fono != null ?
                new ObjectParameter("Fono", fono) :
                new ObjectParameter("Fono", typeof(string));
    
            var persona_EmergenciaParameter = persona_Emergencia != null ?
                new ObjectParameter("Persona_Emergencia", persona_Emergencia) :
                new ObjectParameter("Persona_Emergencia", typeof(string));
    
            var fono_EmergenciaParameter = fono_Emergencia != null ?
                new ObjectParameter("Fono_Emergencia", fono_Emergencia) :
                new ObjectParameter("Fono_Emergencia", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var fecha_NacimientoParameter = fecha_Nacimiento.HasValue ?
                new ObjectParameter("Fecha_Nacimiento", fecha_Nacimiento) :
                new ObjectParameter("Fecha_Nacimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Ins_Empleados", rut_EmpleadoParameter, nombreParameter, apePatParameter, apeMatParameter, id_DeptoParameter, id_CargParameter, anexoParameter, emailEmpParameter, fecha_IncorporacionParameter, rut_EmpresaParameter, id_SexoParameter, id_NacParameter, foto_UsuarioParameter, fecha_DespidoParameter, retiradoParameter, cod_AfpParameter, cod_SaludParameter, calle_PjeParameter, numCasaParameter, vill_PoblParameter, comuna_IdParameter, provincia_IdParameter, fonoParameter, persona_EmergenciaParameter, fono_EmergenciaParameter, emailParameter, fecha_NacimientoParameter);
        }
    
        public virtual int Sp_Ins_Empresas(string rut_emp, string nombre, string direccion, string num, string vilpob, string comu, string ciudad, string fono, string emailemp)
        {
            var rut_empParameter = rut_emp != null ?
                new ObjectParameter("rut_emp", rut_emp) :
                new ObjectParameter("rut_emp", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var numParameter = num != null ?
                new ObjectParameter("num", num) :
                new ObjectParameter("num", typeof(string));
    
            var vilpobParameter = vilpob != null ?
                new ObjectParameter("vilpob", vilpob) :
                new ObjectParameter("vilpob", typeof(string));
    
            var comuParameter = comu != null ?
                new ObjectParameter("comu", comu) :
                new ObjectParameter("comu", typeof(string));
    
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("Ciudad", ciudad) :
                new ObjectParameter("Ciudad", typeof(string));
    
            var fonoParameter = fono != null ?
                new ObjectParameter("fono", fono) :
                new ObjectParameter("fono", typeof(string));
    
            var emailempParameter = emailemp != null ?
                new ObjectParameter("emailemp", emailemp) :
                new ObjectParameter("emailemp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Ins_Empresas", rut_empParameter, nombreParameter, direccionParameter, numParameter, vilpobParameter, comuParameter, ciudadParameter, fonoParameter, emailempParameter);
        }
    
        public virtual int Sp_Ins_LiqSueldo(string rut_Empleado, Nullable<int> id_Tipo_Renumeracion, Nullable<System.DateTime> fecha_Liquidacion, string sueldo_Base, string dias_Trabajados, string porcComision, Nullable<decimal> valor_Com, Nullable<decimal> cant_Horas_Extras, Nullable<decimal> valor_Horas_Extras, Nullable<decimal> gratificacion, Nullable<decimal> bonos, Nullable<decimal> colacion, Nullable<decimal> movilizacion, Nullable<int> codAfp, Nullable<decimal> valor_Afp, Nullable<int> cod_Salud, Nullable<decimal> valor_Salud, Nullable<decimal> id_Seg_Cesantia, Nullable<decimal> valor_Seg_Cesantia, Nullable<decimal> valor_Impuesto, Nullable<decimal> apv, Nullable<decimal> otrs_Descuentos, Nullable<decimal> total_Pagar)
        {
            var rut_EmpleadoParameter = rut_Empleado != null ?
                new ObjectParameter("Rut_Empleado", rut_Empleado) :
                new ObjectParameter("Rut_Empleado", typeof(string));
    
            var id_Tipo_RenumeracionParameter = id_Tipo_Renumeracion.HasValue ?
                new ObjectParameter("Id_Tipo_Renumeracion", id_Tipo_Renumeracion) :
                new ObjectParameter("Id_Tipo_Renumeracion", typeof(int));
    
            var fecha_LiquidacionParameter = fecha_Liquidacion.HasValue ?
                new ObjectParameter("Fecha_Liquidacion", fecha_Liquidacion) :
                new ObjectParameter("Fecha_Liquidacion", typeof(System.DateTime));
    
            var sueldo_BaseParameter = sueldo_Base != null ?
                new ObjectParameter("Sueldo_Base", sueldo_Base) :
                new ObjectParameter("Sueldo_Base", typeof(string));
    
            var dias_TrabajadosParameter = dias_Trabajados != null ?
                new ObjectParameter("Dias_Trabajados", dias_Trabajados) :
                new ObjectParameter("Dias_Trabajados", typeof(string));
    
            var porcComisionParameter = porcComision != null ?
                new ObjectParameter("PorcComision", porcComision) :
                new ObjectParameter("PorcComision", typeof(string));
    
            var valor_ComParameter = valor_Com.HasValue ?
                new ObjectParameter("Valor_Com", valor_Com) :
                new ObjectParameter("Valor_Com", typeof(decimal));
    
            var cant_Horas_ExtrasParameter = cant_Horas_Extras.HasValue ?
                new ObjectParameter("Cant_Horas_Extras", cant_Horas_Extras) :
                new ObjectParameter("Cant_Horas_Extras", typeof(decimal));
    
            var valor_Horas_ExtrasParameter = valor_Horas_Extras.HasValue ?
                new ObjectParameter("Valor_Horas_Extras", valor_Horas_Extras) :
                new ObjectParameter("Valor_Horas_Extras", typeof(decimal));
    
            var gratificacionParameter = gratificacion.HasValue ?
                new ObjectParameter("Gratificacion", gratificacion) :
                new ObjectParameter("Gratificacion", typeof(decimal));
    
            var bonosParameter = bonos.HasValue ?
                new ObjectParameter("Bonos", bonos) :
                new ObjectParameter("Bonos", typeof(decimal));
    
            var colacionParameter = colacion.HasValue ?
                new ObjectParameter("Colacion", colacion) :
                new ObjectParameter("Colacion", typeof(decimal));
    
            var movilizacionParameter = movilizacion.HasValue ?
                new ObjectParameter("Movilizacion", movilizacion) :
                new ObjectParameter("Movilizacion", typeof(decimal));
    
            var codAfpParameter = codAfp.HasValue ?
                new ObjectParameter("CodAfp", codAfp) :
                new ObjectParameter("CodAfp", typeof(int));
    
            var valor_AfpParameter = valor_Afp.HasValue ?
                new ObjectParameter("Valor_Afp", valor_Afp) :
                new ObjectParameter("Valor_Afp", typeof(decimal));
    
            var cod_SaludParameter = cod_Salud.HasValue ?
                new ObjectParameter("Cod_Salud", cod_Salud) :
                new ObjectParameter("Cod_Salud", typeof(int));
    
            var valor_SaludParameter = valor_Salud.HasValue ?
                new ObjectParameter("Valor_Salud", valor_Salud) :
                new ObjectParameter("Valor_Salud", typeof(decimal));
    
            var id_Seg_CesantiaParameter = id_Seg_Cesantia.HasValue ?
                new ObjectParameter("Id_Seg_Cesantia", id_Seg_Cesantia) :
                new ObjectParameter("Id_Seg_Cesantia", typeof(decimal));
    
            var valor_Seg_CesantiaParameter = valor_Seg_Cesantia.HasValue ?
                new ObjectParameter("Valor_Seg_Cesantia", valor_Seg_Cesantia) :
                new ObjectParameter("Valor_Seg_Cesantia", typeof(decimal));
    
            var valor_ImpuestoParameter = valor_Impuesto.HasValue ?
                new ObjectParameter("Valor_Impuesto", valor_Impuesto) :
                new ObjectParameter("Valor_Impuesto", typeof(decimal));
    
            var apvParameter = apv.HasValue ?
                new ObjectParameter("Apv", apv) :
                new ObjectParameter("Apv", typeof(decimal));
    
            var otrs_DescuentosParameter = otrs_Descuentos.HasValue ?
                new ObjectParameter("Otrs_Descuentos", otrs_Descuentos) :
                new ObjectParameter("Otrs_Descuentos", typeof(decimal));
    
            var total_PagarParameter = total_Pagar.HasValue ?
                new ObjectParameter("Total_Pagar", total_Pagar) :
                new ObjectParameter("Total_Pagar", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Ins_LiqSueldo", rut_EmpleadoParameter, id_Tipo_RenumeracionParameter, fecha_LiquidacionParameter, sueldo_BaseParameter, dias_TrabajadosParameter, porcComisionParameter, valor_ComParameter, cant_Horas_ExtrasParameter, valor_Horas_ExtrasParameter, gratificacionParameter, bonosParameter, colacionParameter, movilizacionParameter, codAfpParameter, valor_AfpParameter, cod_SaludParameter, valor_SaludParameter, id_Seg_CesantiaParameter, valor_Seg_CesantiaParameter, valor_ImpuestoParameter, apvParameter, otrs_DescuentosParameter, total_PagarParameter);
        }
    
        public virtual int Sp_Ins_Nacionalidad(string descr)
        {
            var descrParameter = descr != null ?
                new ObjectParameter("Descr", descr) :
                new ObjectParameter("Descr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Ins_Nacionalidad", descrParameter);
        }
    
        public virtual int Sp_Ins_Salud(string nomb_Salud, Nullable<decimal> porc_Cotiz)
        {
            var nomb_SaludParameter = nomb_Salud != null ?
                new ObjectParameter("Nomb_Salud", nomb_Salud) :
                new ObjectParameter("Nomb_Salud", typeof(string));
    
            var porc_CotizParameter = porc_Cotiz.HasValue ?
                new ObjectParameter("Porc_Cotiz", porc_Cotiz) :
                new ObjectParameter("Porc_Cotiz", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Ins_Salud", nomb_SaludParameter, porc_CotizParameter);
        }
    
        public virtual ObjectResult<Sp_Mues_Afp_Result> Sp_Mues_Afp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Mues_Afp_Result>("Sp_Mues_Afp");
        }
    
        public virtual ObjectResult<Sp_Mues_CargFam_Result> Sp_Mues_CargFam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Mues_CargFam_Result>("Sp_Mues_CargFam");
        }
    
        public virtual ObjectResult<Sp_Mues_Comunas_Result> Sp_Mues_Comunas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Mues_Comunas_Result>("Sp_Mues_Comunas");
        }
    
        public virtual ObjectResult<Sp_Mues_Cuidades_Result> Sp_Mues_Cuidades()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Mues_Cuidades_Result>("Sp_Mues_Cuidades");
        }
    
        public virtual ObjectResult<SP_Mues_Empleado_Result> SP_Mues_Empleado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Mues_Empleado_Result>("SP_Mues_Empleado");
        }
    
        public virtual ObjectResult<SP_Mues_Empleado_PDF_Result> SP_Mues_Empleado_PDF(string rut_Emp)
        {
            var rut_EmpParameter = rut_Emp != null ?
                new ObjectParameter("Rut_Emp", rut_Emp) :
                new ObjectParameter("Rut_Emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Mues_Empleado_PDF_Result>("SP_Mues_Empleado_PDF", rut_EmpParameter);
        }
    
        public virtual ObjectResult<Sp_Mues_Empresas_Result> Sp_Mues_Empresas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Mues_Empresas_Result>("Sp_Mues_Empresas");
        }
    
        public virtual ObjectResult<SP_Mues_liqSueldo_Result> SP_Mues_liqSueldo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Mues_liqSueldo_Result>("SP_Mues_liqSueldo");
        }
    
        public virtual ObjectResult<Sp_Mues_Nacionalidad_Result> Sp_Mues_Nacionalidad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Mues_Nacionalidad_Result>("Sp_Mues_Nacionalidad");
        }
    
        public virtual ObjectResult<Sp_Mues_Salud_Result> Sp_Mues_Salud()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Mues_Salud_Result>("Sp_Mues_Salud");
        }
    
        public virtual ObjectResult<Sp_Mues_TipRem_Result> Sp_Mues_TipRem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Mues_TipRem_Result>("Sp_Mues_TipRem");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<Sp_Sel_Afp_Result> Sp_Sel_Afp(Nullable<int> cod_Afp, string nomb_Afp, Nullable<decimal> porcDesc)
        {
            var cod_AfpParameter = cod_Afp.HasValue ?
                new ObjectParameter("Cod_Afp", cod_Afp) :
                new ObjectParameter("Cod_Afp", typeof(int));
    
            var nomb_AfpParameter = nomb_Afp != null ?
                new ObjectParameter("Nomb_Afp", nomb_Afp) :
                new ObjectParameter("Nomb_Afp", typeof(string));
    
            var porcDescParameter = porcDesc.HasValue ?
                new ObjectParameter("PorcDesc", porcDesc) :
                new ObjectParameter("PorcDesc", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Sel_Afp_Result>("Sp_Sel_Afp", cod_AfpParameter, nomb_AfpParameter, porcDescParameter);
        }
    
        public virtual ObjectResult<Sp_Sel_Carg_FamXRutEmpl_Result> Sp_Sel_Carg_FamXRutEmpl(string rut_Empl)
        {
            var rut_EmplParameter = rut_Empl != null ?
                new ObjectParameter("Rut_Empl", rut_Empl) :
                new ObjectParameter("Rut_Empl", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Sel_Carg_FamXRutEmpl_Result>("Sp_Sel_Carg_FamXRutEmpl", rut_EmplParameter);
        }
    
        public virtual ObjectResult<Sp_Sel_CargFamxRut_Result> Sp_Sel_CargFamxRut(string rut_Benef)
        {
            var rut_BenefParameter = rut_Benef != null ?
                new ObjectParameter("Rut_Benef", rut_Benef) :
                new ObjectParameter("Rut_Benef", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Sel_CargFamxRut_Result>("Sp_Sel_CargFamxRut", rut_BenefParameter);
        }
    
        public virtual ObjectResult<Sp_Sel_Cargos_Result> Sp_Sel_Cargos(Nullable<int> id_Tipo)
        {
            var id_TipoParameter = id_Tipo.HasValue ?
                new ObjectParameter("Id_Tipo", id_Tipo) :
                new ObjectParameter("Id_Tipo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Sel_Cargos_Result>("Sp_Sel_Cargos", id_TipoParameter);
        }
    
        public virtual ObjectResult<Sp_Sel_CiudadesxComu_Result> Sp_Sel_CiudadesxComu(Nullable<int> cod_Comu)
        {
            var cod_ComuParameter = cod_Comu.HasValue ?
                new ObjectParameter("Cod_Comu", cod_Comu) :
                new ObjectParameter("Cod_Comu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Sel_CiudadesxComu_Result>("Sp_Sel_CiudadesxComu", cod_ComuParameter);
        }
    
        public virtual ObjectResult<string> SP_Sel_Depto(Nullable<int> idd)
        {
            var iddParameter = idd.HasValue ?
                new ObjectParameter("idd", idd) :
                new ObjectParameter("idd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_Sel_Depto", iddParameter);
        }
    
        public virtual ObjectResult<Sp_Sel_Empleado_Result> Sp_Sel_Empleado(string rut_Emp)
        {
            var rut_EmpParameter = rut_Emp != null ?
                new ObjectParameter("Rut_Emp", rut_Emp) :
                new ObjectParameter("Rut_Emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Sel_Empleado_Result>("Sp_Sel_Empleado", rut_EmpParameter);
        }
    
        public virtual ObjectResult<Sp_Sel_Empresas_Result> Sp_Sel_Empresas(string rut_Empresa)
        {
            var rut_EmpresaParameter = rut_Empresa != null ?
                new ObjectParameter("Rut_Empresa", rut_Empresa) :
                new ObjectParameter("Rut_Empresa", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Sel_Empresas_Result>("Sp_Sel_Empresas", rut_EmpresaParameter);
        }
    
        public virtual ObjectResult<SP_Sel_liqSueldoXRutMes_Result> SP_Sel_liqSueldoXRutMes(string fechLiq, string rut_Emp)
        {
            var fechLiqParameter = fechLiq != null ?
                new ObjectParameter("FechLiq", fechLiq) :
                new ObjectParameter("FechLiq", typeof(string));
    
            var rut_EmpParameter = rut_Emp != null ?
                new ObjectParameter("Rut_Emp", rut_Emp) :
                new ObjectParameter("Rut_Emp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Sel_liqSueldoXRutMes_Result>("SP_Sel_liqSueldoXRutMes", fechLiqParameter, rut_EmpParameter);
        }
    
        public virtual ObjectResult<Sp_Sel_Nacionalidad_Result> Sp_Sel_Nacionalidad(Nullable<int> id_Nac)
        {
            var id_NacParameter = id_Nac.HasValue ?
                new ObjectParameter("id_Nac", id_Nac) :
                new ObjectParameter("id_Nac", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Sel_Nacionalidad_Result>("Sp_Sel_Nacionalidad", id_NacParameter);
        }
    
        public virtual ObjectResult<Sp_Sel_Salud_Result> Sp_Sel_Salud(Nullable<int> cod_Salud, string nombre_Salud, Nullable<decimal> porc_Cotiz)
        {
            var cod_SaludParameter = cod_Salud.HasValue ?
                new ObjectParameter("Cod_Salud", cod_Salud) :
                new ObjectParameter("Cod_Salud", typeof(int));
    
            var nombre_SaludParameter = nombre_Salud != null ?
                new ObjectParameter("Nombre_Salud", nombre_Salud) :
                new ObjectParameter("Nombre_Salud", typeof(string));
    
            var porc_CotizParameter = porc_Cotiz.HasValue ?
                new ObjectParameter("Porc_Cotiz", porc_Cotiz) :
                new ObjectParameter("Porc_Cotiz", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Sel_Salud_Result>("Sp_Sel_Salud", cod_SaludParameter, nombre_SaludParameter, porc_CotizParameter);
        }
    
        public virtual int Sp_UPD_Afp(Nullable<int> cod_Afp, string nomb_Afp, Nullable<decimal> porcDesc)
        {
            var cod_AfpParameter = cod_Afp.HasValue ?
                new ObjectParameter("Cod_Afp", cod_Afp) :
                new ObjectParameter("Cod_Afp", typeof(int));
    
            var nomb_AfpParameter = nomb_Afp != null ?
                new ObjectParameter("Nomb_Afp", nomb_Afp) :
                new ObjectParameter("Nomb_Afp", typeof(string));
    
            var porcDescParameter = porcDesc.HasValue ?
                new ObjectParameter("PorcDesc", porcDesc) :
                new ObjectParameter("PorcDesc", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UPD_Afp", cod_AfpParameter, nomb_AfpParameter, porcDescParameter);
        }
    
        public virtual int Sp_UPD_Carg_Familiar(string rut_benef, string nombre, string apPat, string apMat, string fono1, string fono2, Nullable<System.DateTime> fech_Nac, Nullable<int> id_Sex, string calle_Pje, string numcasa, string vilpob, Nullable<int> comu, Nullable<int> provincia_Id, string email, Nullable<int> id_Nac, string desc)
        {
            var rut_benefParameter = rut_benef != null ?
                new ObjectParameter("Rut_benef", rut_benef) :
                new ObjectParameter("Rut_benef", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apPatParameter = apPat != null ?
                new ObjectParameter("ApPat", apPat) :
                new ObjectParameter("ApPat", typeof(string));
    
            var apMatParameter = apMat != null ?
                new ObjectParameter("ApMat", apMat) :
                new ObjectParameter("ApMat", typeof(string));
    
            var fono1Parameter = fono1 != null ?
                new ObjectParameter("fono1", fono1) :
                new ObjectParameter("fono1", typeof(string));
    
            var fono2Parameter = fono2 != null ?
                new ObjectParameter("fono2", fono2) :
                new ObjectParameter("fono2", typeof(string));
    
            var fech_NacParameter = fech_Nac.HasValue ?
                new ObjectParameter("fech_Nac", fech_Nac) :
                new ObjectParameter("fech_Nac", typeof(System.DateTime));
    
            var id_SexParameter = id_Sex.HasValue ?
                new ObjectParameter("Id_Sex", id_Sex) :
                new ObjectParameter("Id_Sex", typeof(int));
    
            var calle_PjeParameter = calle_Pje != null ?
                new ObjectParameter("Calle_Pje", calle_Pje) :
                new ObjectParameter("Calle_Pje", typeof(string));
    
            var numcasaParameter = numcasa != null ?
                new ObjectParameter("numcasa", numcasa) :
                new ObjectParameter("numcasa", typeof(string));
    
            var vilpobParameter = vilpob != null ?
                new ObjectParameter("vilpob", vilpob) :
                new ObjectParameter("vilpob", typeof(string));
    
            var comuParameter = comu.HasValue ?
                new ObjectParameter("comu", comu) :
                new ObjectParameter("comu", typeof(int));
    
            var provincia_IdParameter = provincia_Id.HasValue ?
                new ObjectParameter("Provincia_Id", provincia_Id) :
                new ObjectParameter("Provincia_Id", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var id_NacParameter = id_Nac.HasValue ?
                new ObjectParameter("Id_Nac", id_Nac) :
                new ObjectParameter("Id_Nac", typeof(int));
    
            var descParameter = desc != null ?
                new ObjectParameter("Desc", desc) :
                new ObjectParameter("Desc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UPD_Carg_Familiar", rut_benefParameter, nombreParameter, apPatParameter, apMatParameter, fono1Parameter, fono2Parameter, fech_NacParameter, id_SexParameter, calle_PjeParameter, numcasaParameter, vilpobParameter, comuParameter, provincia_IdParameter, emailParameter, id_NacParameter, descParameter);
        }
    
        public virtual int Sp_UPD_Cargos(Nullable<int> id_Tipo, string descr)
        {
            var id_TipoParameter = id_Tipo.HasValue ?
                new ObjectParameter("Id_Tipo", id_Tipo) :
                new ObjectParameter("Id_Tipo", typeof(int));
    
            var descrParameter = descr != null ?
                new ObjectParameter("Descr", descr) :
                new ObjectParameter("Descr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UPD_Cargos", id_TipoParameter, descrParameter);
        }
    
        public virtual int Sp_UPD_Depto(Nullable<int> id_depto, string nomDept)
        {
            var id_deptoParameter = id_depto.HasValue ?
                new ObjectParameter("Id_depto", id_depto) :
                new ObjectParameter("Id_depto", typeof(int));
    
            var nomDeptParameter = nomDept != null ?
                new ObjectParameter("NomDept", nomDept) :
                new ObjectParameter("NomDept", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UPD_Depto", id_deptoParameter, nomDeptParameter);
        }
    
        public virtual int Sp_UPD_Empleado(string rut_Empl, string nombre, string apePat, string apeMat, Nullable<int> id_Depto, Nullable<int> id_Carg, string anexo, string emailEmp, string fecha_Incorporacion, string rut_Empresa, Nullable<int> id_Sexo, Nullable<int> id_Nac, byte[] foto_Usuario, Nullable<int> cod_Afp, Nullable<int> cod_Salud, string calle_Pje, string numCasa, string vill_Pobl, Nullable<int> comuna_Id, Nullable<int> provincia_Id, string fono, string persona_Emergencia, string fono_Emergencia, string email, Nullable<System.DateTime> fecha_Nacimiento)
        {
            var rut_EmplParameter = rut_Empl != null ?
                new ObjectParameter("Rut_Empl", rut_Empl) :
                new ObjectParameter("Rut_Empl", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var apePatParameter = apePat != null ?
                new ObjectParameter("ApePat", apePat) :
                new ObjectParameter("ApePat", typeof(string));
    
            var apeMatParameter = apeMat != null ?
                new ObjectParameter("ApeMat", apeMat) :
                new ObjectParameter("ApeMat", typeof(string));
    
            var id_DeptoParameter = id_Depto.HasValue ?
                new ObjectParameter("Id_Depto", id_Depto) :
                new ObjectParameter("Id_Depto", typeof(int));
    
            var id_CargParameter = id_Carg.HasValue ?
                new ObjectParameter("Id_Carg", id_Carg) :
                new ObjectParameter("Id_Carg", typeof(int));
    
            var anexoParameter = anexo != null ?
                new ObjectParameter("Anexo", anexo) :
                new ObjectParameter("Anexo", typeof(string));
    
            var emailEmpParameter = emailEmp != null ?
                new ObjectParameter("EmailEmp", emailEmp) :
                new ObjectParameter("EmailEmp", typeof(string));
    
            var fecha_IncorporacionParameter = fecha_Incorporacion != null ?
                new ObjectParameter("Fecha_Incorporacion", fecha_Incorporacion) :
                new ObjectParameter("Fecha_Incorporacion", typeof(string));
    
            var rut_EmpresaParameter = rut_Empresa != null ?
                new ObjectParameter("Rut_Empresa", rut_Empresa) :
                new ObjectParameter("Rut_Empresa", typeof(string));
    
            var id_SexoParameter = id_Sexo.HasValue ?
                new ObjectParameter("Id_Sexo", id_Sexo) :
                new ObjectParameter("Id_Sexo", typeof(int));
    
            var id_NacParameter = id_Nac.HasValue ?
                new ObjectParameter("Id_Nac", id_Nac) :
                new ObjectParameter("Id_Nac", typeof(int));
    
            var foto_UsuarioParameter = foto_Usuario != null ?
                new ObjectParameter("Foto_Usuario", foto_Usuario) :
                new ObjectParameter("Foto_Usuario", typeof(byte[]));
    
            var cod_AfpParameter = cod_Afp.HasValue ?
                new ObjectParameter("Cod_Afp", cod_Afp) :
                new ObjectParameter("Cod_Afp", typeof(int));
    
            var cod_SaludParameter = cod_Salud.HasValue ?
                new ObjectParameter("Cod_Salud", cod_Salud) :
                new ObjectParameter("Cod_Salud", typeof(int));
    
            var calle_PjeParameter = calle_Pje != null ?
                new ObjectParameter("Calle_Pje", calle_Pje) :
                new ObjectParameter("Calle_Pje", typeof(string));
    
            var numCasaParameter = numCasa != null ?
                new ObjectParameter("NumCasa", numCasa) :
                new ObjectParameter("NumCasa", typeof(string));
    
            var vill_PoblParameter = vill_Pobl != null ?
                new ObjectParameter("Vill_Pobl", vill_Pobl) :
                new ObjectParameter("Vill_Pobl", typeof(string));
    
            var comuna_IdParameter = comuna_Id.HasValue ?
                new ObjectParameter("Comuna_Id", comuna_Id) :
                new ObjectParameter("Comuna_Id", typeof(int));
    
            var provincia_IdParameter = provincia_Id.HasValue ?
                new ObjectParameter("Provincia_Id", provincia_Id) :
                new ObjectParameter("Provincia_Id", typeof(int));
    
            var fonoParameter = fono != null ?
                new ObjectParameter("Fono", fono) :
                new ObjectParameter("Fono", typeof(string));
    
            var persona_EmergenciaParameter = persona_Emergencia != null ?
                new ObjectParameter("Persona_Emergencia", persona_Emergencia) :
                new ObjectParameter("Persona_Emergencia", typeof(string));
    
            var fono_EmergenciaParameter = fono_Emergencia != null ?
                new ObjectParameter("Fono_Emergencia", fono_Emergencia) :
                new ObjectParameter("Fono_Emergencia", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var fecha_NacimientoParameter = fecha_Nacimiento.HasValue ?
                new ObjectParameter("Fecha_Nacimiento", fecha_Nacimiento) :
                new ObjectParameter("Fecha_Nacimiento", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UPD_Empleado", rut_EmplParameter, nombreParameter, apePatParameter, apeMatParameter, id_DeptoParameter, id_CargParameter, anexoParameter, emailEmpParameter, fecha_IncorporacionParameter, rut_EmpresaParameter, id_SexoParameter, id_NacParameter, foto_UsuarioParameter, cod_AfpParameter, cod_SaludParameter, calle_PjeParameter, numCasaParameter, vill_PoblParameter, comuna_IdParameter, provincia_IdParameter, fonoParameter, persona_EmergenciaParameter, fono_EmergenciaParameter, emailParameter, fecha_NacimientoParameter);
        }
    
        public virtual int Sp_UPD_Empresas(string rut_emp, string nombre, string direccion, string num, string vilpob, string comu, string ciudad, string fono, string email)
        {
            var rut_empParameter = rut_emp != null ?
                new ObjectParameter("rut_emp", rut_emp) :
                new ObjectParameter("rut_emp", typeof(string));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("Nombre", nombre) :
                new ObjectParameter("Nombre", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            var numParameter = num != null ?
                new ObjectParameter("num", num) :
                new ObjectParameter("num", typeof(string));
    
            var vilpobParameter = vilpob != null ?
                new ObjectParameter("vilpob", vilpob) :
                new ObjectParameter("vilpob", typeof(string));
    
            var comuParameter = comu != null ?
                new ObjectParameter("comu", comu) :
                new ObjectParameter("comu", typeof(string));
    
            var ciudadParameter = ciudad != null ?
                new ObjectParameter("Ciudad", ciudad) :
                new ObjectParameter("Ciudad", typeof(string));
    
            var fonoParameter = fono != null ?
                new ObjectParameter("fono", fono) :
                new ObjectParameter("fono", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UPD_Empresas", rut_empParameter, nombreParameter, direccionParameter, numParameter, vilpobParameter, comuParameter, ciudadParameter, fonoParameter, emailParameter);
        }
    
        public virtual int Sp_UPD_LiqSueldo(Nullable<int> id_Liq, string rut_Empleado, Nullable<int> id_Tipo_Renumeracion, Nullable<System.DateTime> fecha_Liquidacion, string sueldo_Base, string dias_Trabajados, string porcComision, Nullable<decimal> valor_Com, Nullable<decimal> cant_Horas_Extras, Nullable<decimal> valor_Horas_Extras, Nullable<decimal> gratificacion, Nullable<decimal> bonos, Nullable<decimal> colacion, Nullable<decimal> movilizacion, Nullable<int> codAfp, Nullable<decimal> valor_Afp, Nullable<int> cod_Salud, Nullable<decimal> valor_Salud, Nullable<decimal> valor_Seg_Cesantia, Nullable<decimal> valor_Impuesto, Nullable<decimal> apv, Nullable<decimal> otrs_Descuentos, Nullable<decimal> total_Pagar)
        {
            var id_LiqParameter = id_Liq.HasValue ?
                new ObjectParameter("id_Liq", id_Liq) :
                new ObjectParameter("id_Liq", typeof(int));
    
            var rut_EmpleadoParameter = rut_Empleado != null ?
                new ObjectParameter("Rut_Empleado", rut_Empleado) :
                new ObjectParameter("Rut_Empleado", typeof(string));
    
            var id_Tipo_RenumeracionParameter = id_Tipo_Renumeracion.HasValue ?
                new ObjectParameter("Id_Tipo_Renumeracion", id_Tipo_Renumeracion) :
                new ObjectParameter("Id_Tipo_Renumeracion", typeof(int));
    
            var fecha_LiquidacionParameter = fecha_Liquidacion.HasValue ?
                new ObjectParameter("Fecha_Liquidacion", fecha_Liquidacion) :
                new ObjectParameter("Fecha_Liquidacion", typeof(System.DateTime));
    
            var sueldo_BaseParameter = sueldo_Base != null ?
                new ObjectParameter("Sueldo_Base", sueldo_Base) :
                new ObjectParameter("Sueldo_Base", typeof(string));
    
            var dias_TrabajadosParameter = dias_Trabajados != null ?
                new ObjectParameter("Dias_Trabajados", dias_Trabajados) :
                new ObjectParameter("Dias_Trabajados", typeof(string));
    
            var porcComisionParameter = porcComision != null ?
                new ObjectParameter("PorcComision", porcComision) :
                new ObjectParameter("PorcComision", typeof(string));
    
            var valor_ComParameter = valor_Com.HasValue ?
                new ObjectParameter("Valor_Com", valor_Com) :
                new ObjectParameter("Valor_Com", typeof(decimal));
    
            var cant_Horas_ExtrasParameter = cant_Horas_Extras.HasValue ?
                new ObjectParameter("Cant_Horas_Extras", cant_Horas_Extras) :
                new ObjectParameter("Cant_Horas_Extras", typeof(decimal));
    
            var valor_Horas_ExtrasParameter = valor_Horas_Extras.HasValue ?
                new ObjectParameter("Valor_Horas_Extras", valor_Horas_Extras) :
                new ObjectParameter("Valor_Horas_Extras", typeof(decimal));
    
            var gratificacionParameter = gratificacion.HasValue ?
                new ObjectParameter("Gratificacion", gratificacion) :
                new ObjectParameter("Gratificacion", typeof(decimal));
    
            var bonosParameter = bonos.HasValue ?
                new ObjectParameter("Bonos", bonos) :
                new ObjectParameter("Bonos", typeof(decimal));
    
            var colacionParameter = colacion.HasValue ?
                new ObjectParameter("Colacion", colacion) :
                new ObjectParameter("Colacion", typeof(decimal));
    
            var movilizacionParameter = movilizacion.HasValue ?
                new ObjectParameter("Movilizacion", movilizacion) :
                new ObjectParameter("Movilizacion", typeof(decimal));
    
            var codAfpParameter = codAfp.HasValue ?
                new ObjectParameter("CodAfp", codAfp) :
                new ObjectParameter("CodAfp", typeof(int));
    
            var valor_AfpParameter = valor_Afp.HasValue ?
                new ObjectParameter("Valor_Afp", valor_Afp) :
                new ObjectParameter("Valor_Afp", typeof(decimal));
    
            var cod_SaludParameter = cod_Salud.HasValue ?
                new ObjectParameter("Cod_Salud", cod_Salud) :
                new ObjectParameter("Cod_Salud", typeof(int));
    
            var valor_SaludParameter = valor_Salud.HasValue ?
                new ObjectParameter("Valor_Salud", valor_Salud) :
                new ObjectParameter("Valor_Salud", typeof(decimal));
    
            var valor_Seg_CesantiaParameter = valor_Seg_Cesantia.HasValue ?
                new ObjectParameter("Valor_Seg_Cesantia", valor_Seg_Cesantia) :
                new ObjectParameter("Valor_Seg_Cesantia", typeof(decimal));
    
            var valor_ImpuestoParameter = valor_Impuesto.HasValue ?
                new ObjectParameter("Valor_Impuesto", valor_Impuesto) :
                new ObjectParameter("Valor_Impuesto", typeof(decimal));
    
            var apvParameter = apv.HasValue ?
                new ObjectParameter("Apv", apv) :
                new ObjectParameter("Apv", typeof(decimal));
    
            var otrs_DescuentosParameter = otrs_Descuentos.HasValue ?
                new ObjectParameter("Otrs_Descuentos", otrs_Descuentos) :
                new ObjectParameter("Otrs_Descuentos", typeof(decimal));
    
            var total_PagarParameter = total_Pagar.HasValue ?
                new ObjectParameter("Total_Pagar", total_Pagar) :
                new ObjectParameter("Total_Pagar", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UPD_LiqSueldo", id_LiqParameter, rut_EmpleadoParameter, id_Tipo_RenumeracionParameter, fecha_LiquidacionParameter, sueldo_BaseParameter, dias_TrabajadosParameter, porcComisionParameter, valor_ComParameter, cant_Horas_ExtrasParameter, valor_Horas_ExtrasParameter, gratificacionParameter, bonosParameter, colacionParameter, movilizacionParameter, codAfpParameter, valor_AfpParameter, cod_SaludParameter, valor_SaludParameter, valor_Seg_CesantiaParameter, valor_ImpuestoParameter, apvParameter, otrs_DescuentosParameter, total_PagarParameter);
        }
    
        public virtual int Sp_UPD_LiqSueldoXRutMes(Nullable<int> id_Liq, string rut_Empleado, Nullable<int> id_Tipo_Renumeracion, Nullable<System.DateTime> fecha_Liquidacion, string sueldo_Base, string dias_Trabajados, string porcComision, Nullable<decimal> valor_Com, Nullable<decimal> cant_Horas_Extras, Nullable<decimal> valor_Horas_Extras, Nullable<decimal> gratificacion, Nullable<decimal> bonos, Nullable<decimal> colacion, Nullable<decimal> movilizacion, Nullable<int> codAfp, Nullable<decimal> valor_Afp, Nullable<int> cod_Salud, Nullable<decimal> valor_Salud, Nullable<decimal> id_Seg_Cesantia, Nullable<decimal> valor_Seg_Cesantia, Nullable<decimal> valor_Impuesto, Nullable<decimal> apv, Nullable<decimal> otrs_Descuentos, Nullable<decimal> total_Pagar)
        {
            var id_LiqParameter = id_Liq.HasValue ?
                new ObjectParameter("id_Liq", id_Liq) :
                new ObjectParameter("id_Liq", typeof(int));
    
            var rut_EmpleadoParameter = rut_Empleado != null ?
                new ObjectParameter("Rut_Empleado", rut_Empleado) :
                new ObjectParameter("Rut_Empleado", typeof(string));
    
            var id_Tipo_RenumeracionParameter = id_Tipo_Renumeracion.HasValue ?
                new ObjectParameter("Id_Tipo_Renumeracion", id_Tipo_Renumeracion) :
                new ObjectParameter("Id_Tipo_Renumeracion", typeof(int));
    
            var fecha_LiquidacionParameter = fecha_Liquidacion.HasValue ?
                new ObjectParameter("Fecha_Liquidacion", fecha_Liquidacion) :
                new ObjectParameter("Fecha_Liquidacion", typeof(System.DateTime));
    
            var sueldo_BaseParameter = sueldo_Base != null ?
                new ObjectParameter("Sueldo_Base", sueldo_Base) :
                new ObjectParameter("Sueldo_Base", typeof(string));
    
            var dias_TrabajadosParameter = dias_Trabajados != null ?
                new ObjectParameter("Dias_Trabajados", dias_Trabajados) :
                new ObjectParameter("Dias_Trabajados", typeof(string));
    
            var porcComisionParameter = porcComision != null ?
                new ObjectParameter("PorcComision", porcComision) :
                new ObjectParameter("PorcComision", typeof(string));
    
            var valor_ComParameter = valor_Com.HasValue ?
                new ObjectParameter("Valor_Com", valor_Com) :
                new ObjectParameter("Valor_Com", typeof(decimal));
    
            var cant_Horas_ExtrasParameter = cant_Horas_Extras.HasValue ?
                new ObjectParameter("Cant_Horas_Extras", cant_Horas_Extras) :
                new ObjectParameter("Cant_Horas_Extras", typeof(decimal));
    
            var valor_Horas_ExtrasParameter = valor_Horas_Extras.HasValue ?
                new ObjectParameter("Valor_Horas_Extras", valor_Horas_Extras) :
                new ObjectParameter("Valor_Horas_Extras", typeof(decimal));
    
            var gratificacionParameter = gratificacion.HasValue ?
                new ObjectParameter("Gratificacion", gratificacion) :
                new ObjectParameter("Gratificacion", typeof(decimal));
    
            var bonosParameter = bonos.HasValue ?
                new ObjectParameter("Bonos", bonos) :
                new ObjectParameter("Bonos", typeof(decimal));
    
            var colacionParameter = colacion.HasValue ?
                new ObjectParameter("Colacion", colacion) :
                new ObjectParameter("Colacion", typeof(decimal));
    
            var movilizacionParameter = movilizacion.HasValue ?
                new ObjectParameter("Movilizacion", movilizacion) :
                new ObjectParameter("Movilizacion", typeof(decimal));
    
            var codAfpParameter = codAfp.HasValue ?
                new ObjectParameter("CodAfp", codAfp) :
                new ObjectParameter("CodAfp", typeof(int));
    
            var valor_AfpParameter = valor_Afp.HasValue ?
                new ObjectParameter("Valor_Afp", valor_Afp) :
                new ObjectParameter("Valor_Afp", typeof(decimal));
    
            var cod_SaludParameter = cod_Salud.HasValue ?
                new ObjectParameter("Cod_Salud", cod_Salud) :
                new ObjectParameter("Cod_Salud", typeof(int));
    
            var valor_SaludParameter = valor_Salud.HasValue ?
                new ObjectParameter("Valor_Salud", valor_Salud) :
                new ObjectParameter("Valor_Salud", typeof(decimal));
    
            var id_Seg_CesantiaParameter = id_Seg_Cesantia.HasValue ?
                new ObjectParameter("Id_Seg_Cesantia", id_Seg_Cesantia) :
                new ObjectParameter("Id_Seg_Cesantia", typeof(decimal));
    
            var valor_Seg_CesantiaParameter = valor_Seg_Cesantia.HasValue ?
                new ObjectParameter("Valor_Seg_Cesantia", valor_Seg_Cesantia) :
                new ObjectParameter("Valor_Seg_Cesantia", typeof(decimal));
    
            var valor_ImpuestoParameter = valor_Impuesto.HasValue ?
                new ObjectParameter("Valor_Impuesto", valor_Impuesto) :
                new ObjectParameter("Valor_Impuesto", typeof(decimal));
    
            var apvParameter = apv.HasValue ?
                new ObjectParameter("Apv", apv) :
                new ObjectParameter("Apv", typeof(decimal));
    
            var otrs_DescuentosParameter = otrs_Descuentos.HasValue ?
                new ObjectParameter("Otrs_Descuentos", otrs_Descuentos) :
                new ObjectParameter("Otrs_Descuentos", typeof(decimal));
    
            var total_PagarParameter = total_Pagar.HasValue ?
                new ObjectParameter("Total_Pagar", total_Pagar) :
                new ObjectParameter("Total_Pagar", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UPD_LiqSueldoXRutMes", id_LiqParameter, rut_EmpleadoParameter, id_Tipo_RenumeracionParameter, fecha_LiquidacionParameter, sueldo_BaseParameter, dias_TrabajadosParameter, porcComisionParameter, valor_ComParameter, cant_Horas_ExtrasParameter, valor_Horas_ExtrasParameter, gratificacionParameter, bonosParameter, colacionParameter, movilizacionParameter, codAfpParameter, valor_AfpParameter, cod_SaludParameter, valor_SaludParameter, id_Seg_CesantiaParameter, valor_Seg_CesantiaParameter, valor_ImpuestoParameter, apvParameter, otrs_DescuentosParameter, total_PagarParameter);
        }
    
        public virtual int Sp_UPD_Nacionalidad(Nullable<int> id_Nac, string descr)
        {
            var id_NacParameter = id_Nac.HasValue ?
                new ObjectParameter("Id_Nac", id_Nac) :
                new ObjectParameter("Id_Nac", typeof(int));
    
            var descrParameter = descr != null ?
                new ObjectParameter("Descr", descr) :
                new ObjectParameter("Descr", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UPD_Nacionalidad", id_NacParameter, descrParameter);
        }
    
        public virtual int Sp_UPD_Salud(Nullable<int> cod_Salud, string nombre_Salud, Nullable<decimal> porc_Cotiz)
        {
            var cod_SaludParameter = cod_Salud.HasValue ?
                new ObjectParameter("Cod_Salud", cod_Salud) :
                new ObjectParameter("Cod_Salud", typeof(int));
    
            var nombre_SaludParameter = nombre_Salud != null ?
                new ObjectParameter("Nombre_Salud", nombre_Salud) :
                new ObjectParameter("Nombre_Salud", typeof(string));
    
            var porc_CotizParameter = porc_Cotiz.HasValue ?
                new ObjectParameter("Porc_Cotiz", porc_Cotiz) :
                new ObjectParameter("Porc_Cotiz", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_UPD_Salud", cod_SaludParameter, nombre_SaludParameter, porc_CotizParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Sp_Mues_Afp_ID_Result> Sp_Mues_Afp_ID(Nullable<int> idAFP)
        {
            var idAFPParameter = idAFP.HasValue ?
                new ObjectParameter("idAFP", idAFP) :
                new ObjectParameter("idAFP", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Mues_Afp_ID_Result>("Sp_Mues_Afp_ID", idAFPParameter);
        }
    
        public virtual ObjectResult<Sp_Mues_Salud_ID_Result> Sp_Mues_Salud_ID(Nullable<int> idsal)
        {
            var idsalParameter = idsal.HasValue ?
                new ObjectParameter("idsal", idsal) :
                new ObjectParameter("idsal", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Mues_Salud_ID_Result>("Sp_Mues_Salud_ID", idsalParameter);
        }
    
        public virtual ObjectResult<Sp_Mues_Seg_Cesantia_Result> Sp_Mues_Seg_Cesantia()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Mues_Seg_Cesantia_Result>("Sp_Mues_Seg_Cesantia");
        }
    
        public virtual ObjectResult<Sp_Sel_Seg_Cesantia_Id_Result> Sp_Sel_Seg_Cesantia_Id(Nullable<int> idtipcon)
        {
            var idtipconParameter = idtipcon.HasValue ?
                new ObjectParameter("idtipcon", idtipcon) :
                new ObjectParameter("idtipcon", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sp_Sel_Seg_Cesantia_Id_Result>("Sp_Sel_Seg_Cesantia_Id", idtipconParameter);
        }
    }
}
