//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvcSp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Salud
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salud()
        {
            this.Empleados = new HashSet<Empleados>();
        }

        [Key]
        [Display(Name = "Código Salud")]
        public int Cod_Salud { get; set; }

        [Display(Name = "Nombre Inst. Salud")]
        [Required(ErrorMessage = "Dato Obligatorio")]
        public string Nombre_Salud { get; set; }

        [Display(Name = "Porcentaje Salud")]
        [Required(ErrorMessage = "Dato Obligatorio")]
        public Nullable<decimal> Porc_Cotiz { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleados> Empleados { get; set; }
    }
}
