//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudMvcSp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablImpDiario
    {
        public int Id_Factor_Diario { get; set; }
        public Nullable<decimal> Desde { get; set; }
        public Nullable<decimal> Hasta { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> CantAReb { get; set; }
        public Nullable<decimal> TasaImpEfec { get; set; }
    }
}
